[[build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value =  "17"
[[build.env]]
name = "GOOGLE_FUNCTION_SIGNATURE_TYPE"
value =  "event"
# value =  "event"
# value =  "http"
[[build.env]]
name = "GOOGLE_FUNCTION_TARGET"
value =  "com.onebank.taskmaster.sendnotification.function.SendEmailNotificationFunctionEntryPoint"
[build]
builder = "gcr.io/buildpacks/builder:google-22"